firefox 124.0.1

diff --git a/www-client/firefox/le.patch b/www-client/firefox/le.patch
--- a/www-client/firefox/le.patch
+++ b/www-client/firefox/le.patch
@@ -1,302 +1,102 @@
---- firefox-118.0.1.ebuild.orig	2023-10-03 18:11:04.000000000 +0200
-+++ firefox-118.0.1.ebuild	2023-10-10 02:37:28.873439976 +0200
-@@ -5,7 +5,7 @@ EAPI=8
+--- firefox-124.0.1.ebuild	2024-02-25 17:57:40.890024443 +0100
++++ firefox-124.0.1.ebuild	2024-03-24 19:10:58.000000000 +0100
+@@ -3,11 +3,11 @@
  
- FIREFOX_PATCHSET="firefox-118-patches-02.tar.xz"
+ EAPI=8
  
--LLVM_MAX_SLOT=16
-+LLVM_MAX_SLOT=17
+-FIREFOX_PATCHSET="firefox-123-patches-03.tar.xz"
++FIREFOX_PATCHSET="firefox-124-patches-01.tar.xz"
  
- PYTHON_COMPAT=( python3_{10..11} )
+ LLVM_COMPAT=( 16 17 )
+ 
+-PYTHON_COMPAT=( python3_{10..11} )
++PYTHON_COMPAT=( python3_{10..12} )
  PYTHON_REQ_USE="ncurses,sqlite,ssl"
-@@ -64,7 +64,8 @@ LICENSE="MPL-2.0 GPL-2 LGPL-2.1"
- IUSE="+clang cpu_flags_arm_neon dbus debug eme-free hardened hwaccel"
- IUSE+=" jack +jumbo-build libproxy lto openh264 pgo pulseaudio sndio selinux"
- IUSE+=" +system-av1 +system-harfbuzz +system-icu +system-jpeg +system-libevent +system-libvpx system-png system-python-libs +system-webp"
--IUSE+=" +telemetry valgrind wayland wifi +X"
-+#IUSE+=" -telemetry wayland wifi +X"
-+IUSE+=" -telemetry valgrind wayland wifi +X"
  
- # Firefox-only IUSE
- IUSE+=" geckodriver +gmp-autoupdate screencast"
-@@ -81,6 +82,15 @@ FF_ONLY_DEPEND="!www-client/firefox:0
- BDEPEND="${PYTHON_DEPS}
- 	|| (
- 		(
-+			sys-devel/clang:17
-+			sys-devel/llvm:17
-+			clang? (
-+				sys-devel/lld:17
-+				virtual/rust:0/llvm-17
-+				pgo? ( =sys-libs/compiler-rt-sanitizers-17*[profile] )
-+			)
-+		)
-+		(
- 			sys-devel/clang:16
- 			sys-devel/llvm:16
- 			clang? (
-@@ -89,15 +99,6 @@ BDEPEND="${PYTHON_DEPS}
- 				pgo? ( =sys-libs/compiler-rt-sanitizers-16*[profile] )
- 			)
- 		)
--		(
--			sys-devel/clang:15
--			sys-devel/llvm:15
--			clang? (
--				sys-devel/lld:15
--				virtual/rust:0/llvm-15
--				pgo? ( =sys-libs/compiler-rt-sanitizers-15*[profile] )
--			)
--		)
- 	)
- 	app-alternatives/awk
- 	app-arch/unzip
-@@ -597,23 +598,23 @@ pkg_setup() {
- 			ewarn "/dev/shm is not mounted -- expect build failures!"
+ WANT_AUTOCONF="2.1"
+@@ -121,7 +121,7 @@ COMMON_DEPEND="${FF_ONLY_DEPEND}
+ 	dev-libs/expat
+ 	dev-libs/glib:2
+ 	dev-libs/libffi:=
+-	>=dev-libs/nss-3.97
++	>=dev-libs/nss-3.98
+ 	>=dev-libs/nspr-4.35
+ 	media-libs/alsa-lib
+ 	media-libs/fontconfig
+@@ -458,8 +458,6 @@ virtwl() {
+ 	[[ -n $XDG_RUNTIME_DIR ]] || die "${FUNCNAME} needs XDG_RUNTIME_DIR to be set; try xdg_environment_reset"
+ 	tinywl -h >/dev/null || die 'tinywl -h failed'
+ 
+-	# TODO: don't run addpredict in utility function. WLR_RENDERER=pixman doesn't work
+-	addpredict /dev/dri
+ 	local VIRTWL VIRTWL_PID
+ 	coproc VIRTWL { WLR_BACKENDS=headless exec tinywl -s 'echo $WAYLAND_DISPLAY; read _; kill $PPID'; }
+ 	local -x WAYLAND_DISPLAY
+@@ -555,34 +553,8 @@ pkg_setup() {
+ 			# (PORTAGE_SCHEDULING_POLICY) update...
+ 			addpredict /proc
+ 
+-			# May need a wider addpredict when using wayland+pgo.
+-			addpredict /dev/dri
+-
+-			# Allow access to GPU during PGO run
+-			local ati_cards mesa_cards nvidia_cards render_cards
+-			shopt -s nullglob
+-
+-			ati_cards=$(echo -n /dev/ati/card* | sed 's/ /:/g')
+-			if [[ -n "${ati_cards}" ]] ; then
+-				addpredict "${ati_cards}"
+-			fi
+-
+-			mesa_cards=$(echo -n /dev/dri/card* | sed 's/ /:/g')
+-			if [[ -n "${mesa_cards}" ]] ; then
+-				addpredict "${mesa_cards}"
+-			fi
+-
+-			nvidia_cards=$(echo -n /dev/nvidia* | sed 's/ /:/g')
+-			if [[ -n "${nvidia_cards}" ]] ; then
+-				addpredict "${nvidia_cards}"
+-			fi
+-
+-			render_cards=$(echo -n /dev/dri/renderD128* | sed 's/ /:/g')
+-			if [[ -n "${render_cards}" ]] ; then
+-				addpredict "${render_cards}"
+-			fi
+-
+-			shopt -u nullglob
++			# Clear tons of conditions, since PGO is hardware-dependant.
++			addpredict /dev
  		fi
  
--		# Google API keys (see http://www.chromium.org/developers/how-tos/api-keys)
--		# Note: These are for Gentoo Linux use ONLY. For your own distribution, please
--		# get your own set of keys.
--		if [[ -z "${MOZ_API_KEY_GOOGLE+set}" ]] ; then
--			MOZ_API_KEY_GOOGLE="AIzaSyDEAOvatFogGaPi0eTgsV_ZlEzx0ObmepsMzfAc"
--		fi
--
--		if [[ -z "${MOZ_API_KEY_LOCATION+set}" ]] ; then
--			MOZ_API_KEY_LOCATION="AIzaSyB2h2OuRgGaPicUgy5N-5hsZqiPW6sH3n_rptiQ"
--		fi
--
--		# Mozilla API keys (see https://location.services.mozilla.com/api)
--		# Note: These are for Gentoo Linux use ONLY. For your own distribution, please
--		# get your own set of keys.
--		if [[ -z "${MOZ_API_KEY_MOZILLA+set}" ]] ; then
--			MOZ_API_KEY_MOZILLA="edb3d487-3a84-46m0ap1e3-9dfd-92b5efaaa005"
--		fi
-+#		# Google API keys (see http://www.chromium.org/developers/how-tos/api-keys)
-+#		# Note: These are for Gentoo Linux use ONLY. For your own distribution, please
-+#		# get your own set of keys.
-+#		if [[ -z "${MOZ_API_KEY_GOOGLE+set}" ]] ; then
-+#			MOZ_API_KEY_GOOGLE="AIzaSyDEAOvatFogGaPi0eTgsV_ZlEzx0ObmepsMzfAc"
-+#		fi
-+#
-+#		if [[ -z "${MOZ_API_KEY_LOCATION+set}" ]] ; then
-+#			MOZ_API_KEY_LOCATION="AIzaSyB2h2OuRgGaPicUgy5N-5hsZqiPW6sH3n_rptiQ"
-+#		fi
-+#
-+#		# Mozilla API keys (see https://location.services.mozilla.com/api)
-+#		# Note: These are for Gentoo Linux use ONLY. For your own distribution, please
-+#		# get your own set of keys.
-+#		if [[ -z "${MOZ_API_KEY_MOZILLA+set}" ]] ; then
-+#			MOZ_API_KEY_MOZILLA="edb3d487-3a84-46m0ap1e3-9dfd-92b5efaaa005"
-+#		fi
- 
- 		# Ensure we use C locale when building, bug #746215
- 		export LC_ALL=C
-@@ -676,6 +677,8 @@ src_prepare() {
- 		"${S}"/python/mozbuild/mozbuild/configure/check_debug_ranges.py \
- 		|| die "sed failed to set toolchain prefix"
- 
-+	#Allow disabling ccache stats here otherwise you get this: https://bugzilla.mozilla.org/show_bug.cgi?id=1742849
-+	#or similar, like: Failed to parse ccache stats output: 'Uncacheable/Compiler produced empty output' '6038'
- 	sed -i \
- 		-e 's/ccache_stats = None/return None/' \
- 		"${S}"/python/mozbuild/mozbuild/controller/building.py \
-@@ -709,10 +712,11 @@ src_prepare() {
- 	BUILD_DIR="${WORKDIR}/${PN}_build"
- 	mkdir -p "${BUILD_DIR}" || die
- 
--	# Write API keys to disk
--	echo -n "${MOZ_API_KEY_GOOGLE//gGaPi/}" > "${S}"/api-google.key || die
--	echo -n "${MOZ_API_KEY_LOCATION//gGaPi/}" > "${S}"/api-location.key || die
--	echo -n "${MOZ_API_KEY_MOZILLA//m0ap1/}" > "${S}"/api-mozilla.key || die
-+	## Write API keys to disk
-+	#echo -n "${MOZ_API_KEY_GOOGLE//gGaPi/}" > "${S}"/api-google.key || die
-+	#echo -n "${MOZ_API_KEY_LOCATION//gGaPi/}" > "${S}"/api-location.key || die
-+	#echo -n "${MOZ_API_KEY_MOZILLA//m0ap1/}" > "${S}"/api-mozilla.key || die
-+	rm -f "${S}"/api-google.key "${S}"/api-location.key "${S}"/api-mozilla.key
- 
- 	xdg_environment_reset
- }
-@@ -797,6 +801,48 @@ src_configure() {
- 		export MOZILLA_OFFICIAL=1
+ 		if ! mountpoint -q /dev/shm ; then
+@@ -1080,16 +1052,15 @@ src_configure() {
  	fi
  
-+	#TODO: why did I do these before the other settings? wouldn't they potentially get overridden?!
-+	#mozconfig_add_options_ac 'gotchas' \
-+	#	--disable-more-deterministic
-+	#^ because 84 failed tests(and Object's keys order is sorted!ie. it breaks the web): https://bugs.gentoo.org/717374 and https://bugzilla.mozilla.org/show_bug.cgi?id=1542951
-+	#08 may 2021: www-client/firefox-88.0.1:  0:01.89 mozbuild.configure.options.InvalidOptionError: Unknown option: --disable-more-deterministic
+ 	# elf-hack
++	# Filter "-z,pack-relative-relocs" and let the build system handle it instead. 
+ 	if use amd64 || use x86 ; then
++		filter-flags "-z,pack-relative-relocs"
 +
-+	mozconfig_add_options_ac 'just making sure' \
-+		--disable-artifact-builds
-+	# https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Build_Instructions/Artifact_builds
-+
-+
-+		#--without-ccache \
-+	mozconfig_add_options_ac 'with ccache' \
-+		--with-ccache=/usr/bin/ccache
-+
-+
-+	# 0:02.41 mozbuild.configure.options.InvalidOptionError: --enable-system-ffi is not available in this configuration
-+		#--with-system-ffi \
-+	# 0:02.39 mozbuild.configure.options.InvalidOptionError: --with-system-ffi is not available in this configuration
-+
-+	#mozconfig_add_options_ac 'probably needs to be enabled' \
-+	#	--disable-ctypes
-+	#XXX: ^ that --disable-ctypes will cause --enable-system-ffi to not be recognized as valid option!
-+
-+		#--enable-cpp-rtti \
-+	mozconfig_add_options_ac 'must be enabled or else --enable-system-ffi to not be recognized as valid option, at least!' \
-+		--enable-ctypes
-+	#js-ctypes allows application and extension code to call back and forth to native code written in C. C++ support is possible through vtable pointers see Using COM from js-ctypes.
-+#src: https://developer.mozilla.org/en-US/docs/Mozilla/js-ctypes
-+#XXX: if you disable this, you'll get the following(maybe also the core dump because of it): firefox-hg $ ./mach run
-+# 0:00.89 /tmp/obj-x86_64-pc-linux-gnu/dist/bin/firefox -no-remote -profile /tmp/obj-x86_64-pc-linux-gnu/tmp/scratch_user
-+#JavaScript error: resource://gre/modules/osfile/osfile_shared_allthreads.jsm, line 92: NS_ERROR_FILE_NOT_FOUND: Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIXPCComponents_Utils.import]
-+#[27108] WARNING: Cannot create startup observer : service,@mozilla.org/weave/service;1: file /home/z/build/1packages/firefox-hg/makepkg_pacman/firefox-hg/src/firefox-hg/embedding/components/appstartup/nsAppStartupNotifier.cpp, line 81
-+
-+	#removed from 'Gentoo default':
-+		#--allow-addon-sideload \
-+		#^  if update channel is esr then this is true! so careful!
-+		#--without-ccache \
-+
-+		#--allow-addon-sideload \
-+		#--without-ccache \
-+
- 	mozconfig_add_options_ac 'Gentoo default' \
- 		--allow-addon-sideload \
- 		--disable-cargo-incremental \
-@@ -836,13 +882,74 @@ src_configure() {
- 		--x-libraries="${ESYSROOT}/usr/$(get_libdir)"
- 
- 	# Set update channel
--	local update_channel=release
--	[[ -n ${MOZ_ESR} ]] && update_channel=esr
--	mozconfig_add_options_ac '' --update-channel=${update_channel}
-+	#local update_channel=release
-+	#[[ -n ${MOZ_ESR} ]] && update_channel=esr
-+	#mozconfig_add_options_ac '' --update-channel=${update_channel}
-+	mozconfig_add_options_ac 'from old mozconfig' --disable-update-channel
-+
-+		#on 97.0.2, 08march2022 the following options don't exist anymore:
-+		#'--enable-extensions=default,-skipgnomevfs,-skipgio' \ # 0:01.62 mozbuild.configure.options.InvalidOptionError: Unknown option: --enable-extensions
-+		#--disable-tasktracer \
-+		#--enable-xul \
-+		#on 103.0 28 july 2022, doesn't exist:
-+		#--disable-verify-mar \
-+
-+	# spacer
-+
-+	mozconfig_add_options_ac 'from old mozconfig' \
-+		--disable-valgrind \
-+		--disable-jprof \
-+		--disable-instruments \
-+		--disable-callgrind \
-+		--disable-dtrace \
-+		--disable-libproxy \
-+		--disable-accessibility \
-+		--disable-webrtc \
-+		--disable-raw \
-+		--disable-wmf \
-+		--enable-ffmpeg \
-+		--disable-system-extension-dirs \
-+		--disable-parental-controls \
-+		--enable-sandbox \
-+		--disable-logrefcnt \
-+		--disable-dump-painting \
-+		--disable-stdcxx-compat \
-+		--disable-startupcache \
-+		--disable-webspeech \
-+		--disable-synth-speechd \
-+		--disable-webspeechtestbackend \
-+		--disable-tests \
-+		--disable-vtune
- 
--	if ! use x86 && [[ ${CHOST} != armv*h* ]] ; then
--		mozconfig_add_options_ac '' --enable-rust-simd
--	fi
-+	# in firefox 118.0.1
-+	# 0:00.81 mozbuild.configure.options.InvalidOptionError: Unknown option: --enable-fmp4
-+		#--enable-fmp4 \
-+
-+
-+	#see more flags in ${WORKDIR}/firefox-83.0/toolkit/moz.configure
-+
-+	#FIXME: can't disable printing due to errors because it's not guarded, ie. firefox devs don't expect it to ever be disabled so they don't compile against it.
-+		#--disable-printing \
-+		#16:19.17 /var/tmp/portage/www-client/firefox-83.0/work/firefox-83.0/widget/nsPrintSettingsImpl.cpp:821:24: error: use of undeclared identifier 'PR_GetEnv'
-+	mozconfig_add_options_ac 'possible source of issues unless toggled' \
-+		--disable-profiling \
-+		--disable-dmd \
-+		--disable-cpp-rtti
-+			# #DMD (short for "dark matter detector") is a heap profiler within Firefox. https://developer.mozilla.org/en-US/docs/Mozilla/Performance/DMD
-+
-+
-+	#--disable-system-pixman #used to be disabled on archlinux because:  ^ can't find pixman.h !
-+	# already handled when using USE=clang :: --disable-elf-hack
-+	# --------------
-+#	if ! use x86 && [[ ${CHOST} != armv*h* ]] ; then
-+#		mozconfig_add_options_ac '' --enable-rust-simd
-+#		#well this gives me errors like this:
-+## 4:01.36 error: unrecognized platform-specific intrinsic function: `simd_shuffle2`
-+## 4:01.36   --> /var/tmp/portage/www-client/firefox-118.0.1/work/firefox-118.0.1/third_party/rust/packed_simd_2/src/codegen/llvm.rs:10:5
-+## 4:01.36    |
-+## 4:01.36 10 |     pub fn simd_shuffle2<T, U>(x: T, y: T, idx: [u32; 2]) -> U;
-+## 4:01.36    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
-+#	fi
- 
- 	# For future keywording: This is currently (97.0) only supported on:
- 	# amd64, arm, arm64 & x86.
-@@ -989,10 +1096,15 @@ src_configure() {
- 
- 	mozconfig_use_enable debug
- 	if use debug ; then
--		mozconfig_add_options_ac '+debug' --disable-optimize
-+		#mozconfig_add_options_ac '+debug' --disable-optimize
-+		mozconfig_add_options_ac '+debug but do we want it for JS too? say yes for now' --enable-debug-js-modules
- 		mozconfig_add_options_ac '+debug' --enable-real-time-tracing
-+		#^ i haven't checked this to see if i need it or i don't!
- 	else
--		mozconfig_add_options_ac 'Gentoo defaults' --disable-real-time-tracing
-+		mozconfig_add_options_ac 'normal non-debug build' --disable-debug-js-modules
-+	fi
-+	mozconfig_add_options_ac 'Gentoo defaults' --disable-real-time-tracing
-+	#the -ggdb thing isn't dependent on USE=debug from now on:
- 
- 		if is-flag '-g*' ; then
- 			if use clang ; then
-@@ -1017,7 +1129,7 @@ src_configure() {
+ 		if tc-ld-is-mold ; then
+ 			# relr-elf-hack is currently broken with mold, bgo#916259
+ 			mozconfig_add_options_ac 'disable elf-hack with mold linker' --disable-elf-hack
  		else
- 			mozconfig_add_options_ac "Gentoo default" --enable-optimize=-O2
+-			if use clang ; then
+-				mozconfig_add_options_ac 'relr elf-hack with clang' --enable-elf-hack=relr
+-			else
+-				mozconfig_add_options_ac 'legacy elf-hack with gcc' --enable-elf-hack=legacy
+-			fi
++			mozconfig_add_options_ac 'relr elf-hack' --enable-elf-hack=relr
  		fi
--	fi
-+	#fi
+ 	elif use ppc64 ; then
+ 		# '--disable-elf-hack' is not recognized on ppc64, bgo#917049
+@@ -1121,6 +1092,9 @@ src_configure() {
+ 		mozconfig_add_options_ac 'valgrind requirement' --disable-jemalloc
+ 	fi
  
- 	# Debug flag was handled via configure
- 	filter-flags '-g*'
-@@ -1126,6 +1238,25 @@ src_configure() {
- 
- 	# Disable notification when build system has finished
- 	export MOZ_NOSPAM=1
-+	#me
-+	export -n MOZ_TELEMETRY_REPORTING
-+	unset MOZ_TELEMETRY_REPORTING
++	# System-av1 fix
++	use system-av1 && append-ldflags "-Wl,--undefined-version"
 +
-+	#unsure if any effect: (but a patch is already rendering the use of this moot)
-+	export -n MOZ_TELEMETRY_ON_BY_DEFAULT
-+	unset MOZ_TELEMETRY_ON_BY_DEFAULT
-+
-+	#actually forget this, I'm patching it to FALSE in sources! 08 March 2022
-+	##export MOZ_ADDON_SIGNING=1 #yup this was 1 even tho MOZ_REQUIRE_SIGNING=0
-+	#export MOZ_ADDON_SIGNING=0 #this setting may not be used at all currently on 97.0.2 but just setting it to 0 anyway
-+	##export MOZ_REQUIRE_SIGNING=0 # 0:01.63 mozbuild.configure.options.InvalidOptionError: MOZ_REQUIRE_SIGNING takes 0 values
-+	#export -n MOZ_REQUIRE_SIGNING
-+	#unset MOZ_REQUIRE_SIGNING
-+	#MOZ_REQUIRE_SIGNING=
-+	##^yup, it should be empty and work as if it's set to disabled!
-+	#export MOZ_REQUIRE_SIGNING
-+	#end of me
-+
- 
- 	# Portage sets XARGS environment variable to "xargs -r" by default which
- 	# breaks build system's check_prog() function which doesn't support arguments
+ 	# Allow elfhack to work in combination with unstripped binaries
+ 	# when they would normally be larger than 2GiB.
+ 	append-ldflags "-Wl,--compress-debug-sections=zlib"
