firefox-127.0

diff --git a/www-client/firefox/le.patch b/www-client/firefox/le.patch
--- a/www-client/firefox/le.patch
+++ b/www-client/firefox/le.patch
@@ -1,102 +1,53 @@
---- firefox-124.0.1.ebuild	2024-02-25 17:57:40.890024443 +0100
-+++ firefox-124.0.1.ebuild	2024-03-24 19:10:58.000000000 +0100
-@@ -3,11 +3,11 @@
+--- firefox-126.0.ebuild	2024-05-19 08:49:39.645204963 +0200
++++ firefox-127.0.ebuild	2024-06-13 11:43:57.789862308 +0200
+@@ -3,9 +3,9 @@
  
  EAPI=8
  
--FIREFOX_PATCHSET="firefox-123-patches-03.tar.xz"
-+FIREFOX_PATCHSET="firefox-124-patches-01.tar.xz"
+-FIREFOX_PATCHSET="firefox-126-patches-01.tar.xz"
++FIREFOX_PATCHSET="firefox-127-patches-02.tar.xz"
  
- LLVM_COMPAT=( 16 17 )
+-LLVM_COMPAT=( 17 )
++LLVM_COMPAT=( 17 18 )
  
--PYTHON_COMPAT=( python3_{10..11} )
-+PYTHON_COMPAT=( python3_{10..12} )
+ PYTHON_COMPAT=( python3_{10..12} )
  PYTHON_REQ_USE="ncurses,sqlite,ssl"
+@@ -69,8 +69,6 @@ IUSE+=" -telemetry valgrind wayland wifi
+ # Firefox-only IUSE
+ IUSE+=" geckodriver +gmp-autoupdate"
  
- WANT_AUTOCONF="2.1"
-@@ -121,7 +121,7 @@ COMMON_DEPEND="${FF_ONLY_DEPEND}
+-# "-jumbo-build +system-icu": build failure on firefox-120:
+-#   firefox-120.0/intl/components/src/TimeZone.cpp:345:3: error: use of undeclared identifier 'MOZ_TRY'
+ REQUIRED_USE="|| ( X wayland )
+ 	debug? ( !system-av1 )
+ 	pgo? ( lto )
+@@ -95,7 +93,7 @@ BDEPEND="${PYTHON_DEPS}
+ 	>=dev-util/cbindgen-0.26.0
+ 	net-libs/nodejs
+ 	virtual/pkgconfig
+-	!clang? ( >=virtual/rust-1.74 )
++	!clang? ( >=virtual/rust-1.76 )
+ 	!elibc_glibc? ( dev-lang/rust )
+ 	amd64? ( >=dev-lang/nasm-2.14 )
+ 	x86? ( >=dev-lang/nasm-2.14 )
+@@ -106,7 +104,10 @@ BDEPEND="${PYTHON_DEPS}
+ 			x11-apps/xhost
+ 		)
+ 		!X? (
+-			>=gui-libs/wlroots-0.15.1-r1[tinywl]
++			|| (
++				gui-wm/tinywl
++				<gui-libs/wlroots-0.17.3[tinywl(-)]
++			)
+ 			x11-misc/xkeyboard-config
+ 		)
+ 	)"
+@@ -115,7 +116,7 @@ COMMON_DEPEND="${FF_ONLY_DEPEND}
  	dev-libs/expat
  	dev-libs/glib:2
  	dev-libs/libffi:=
--	>=dev-libs/nss-3.97
-+	>=dev-libs/nss-3.98
+-	>=dev-libs/nss-3.99
++	>=dev-libs/nss-3.100
  	>=dev-libs/nspr-4.35
  	media-libs/alsa-lib
  	media-libs/fontconfig
-@@ -458,8 +458,6 @@ virtwl() {
- 	[[ -n $XDG_RUNTIME_DIR ]] || die "${FUNCNAME} needs XDG_RUNTIME_DIR to be set; try xdg_environment_reset"
- 	tinywl -h >/dev/null || die 'tinywl -h failed'
- 
--	# TODO: don't run addpredict in utility function. WLR_RENDERER=pixman doesn't work
--	addpredict /dev/dri
- 	local VIRTWL VIRTWL_PID
- 	coproc VIRTWL { WLR_BACKENDS=headless exec tinywl -s 'echo $WAYLAND_DISPLAY; read _; kill $PPID'; }
- 	local -x WAYLAND_DISPLAY
-@@ -555,34 +553,8 @@ pkg_setup() {
- 			# (PORTAGE_SCHEDULING_POLICY) update...
- 			addpredict /proc
- 
--			# May need a wider addpredict when using wayland+pgo.
--			addpredict /dev/dri
--
--			# Allow access to GPU during PGO run
--			local ati_cards mesa_cards nvidia_cards render_cards
--			shopt -s nullglob
--
--			ati_cards=$(echo -n /dev/ati/card* | sed 's/ /:/g')
--			if [[ -n "${ati_cards}" ]] ; then
--				addpredict "${ati_cards}"
--			fi
--
--			mesa_cards=$(echo -n /dev/dri/card* | sed 's/ /:/g')
--			if [[ -n "${mesa_cards}" ]] ; then
--				addpredict "${mesa_cards}"
--			fi
--
--			nvidia_cards=$(echo -n /dev/nvidia* | sed 's/ /:/g')
--			if [[ -n "${nvidia_cards}" ]] ; then
--				addpredict "${nvidia_cards}"
--			fi
--
--			render_cards=$(echo -n /dev/dri/renderD128* | sed 's/ /:/g')
--			if [[ -n "${render_cards}" ]] ; then
--				addpredict "${render_cards}"
--			fi
--
--			shopt -u nullglob
-+			# Clear tons of conditions, since PGO is hardware-dependant.
-+			addpredict /dev
- 		fi
- 
- 		if ! mountpoint -q /dev/shm ; then
-@@ -1080,16 +1052,15 @@ src_configure() {
- 	fi
- 
- 	# elf-hack
-+	# Filter "-z,pack-relative-relocs" and let the build system handle it instead. 
- 	if use amd64 || use x86 ; then
-+		filter-flags "-z,pack-relative-relocs"
-+
- 		if tc-ld-is-mold ; then
- 			# relr-elf-hack is currently broken with mold, bgo#916259
- 			mozconfig_add_options_ac 'disable elf-hack with mold linker' --disable-elf-hack
- 		else
--			if use clang ; then
--				mozconfig_add_options_ac 'relr elf-hack with clang' --enable-elf-hack=relr
--			else
--				mozconfig_add_options_ac 'legacy elf-hack with gcc' --enable-elf-hack=legacy
--			fi
-+			mozconfig_add_options_ac 'relr elf-hack' --enable-elf-hack=relr
- 		fi
- 	elif use ppc64 ; then
- 		# '--disable-elf-hack' is not recognized on ppc64, bgo#917049
-@@ -1121,6 +1092,9 @@ src_configure() {
- 		mozconfig_add_options_ac 'valgrind requirement' --disable-jemalloc
- 	fi
- 
-+	# System-av1 fix
-+	use system-av1 && append-ldflags "-Wl,--undefined-version"
-+
- 	# Allow elfhack to work in combination with unstripped binaries
- 	# when they would normally be larger than 2GiB.
- 	append-ldflags "-Wl,--compress-debug-sections=zlib"
diff --git a/www-client/firefox/moo.patch b/www-client/firefox/moo.patch
--- a/www-client/firefox/moo.patch
+++ b/www-client/firefox/moo.patch
@@ -1,121 +1,53 @@
---- direfox-124.0.1.ebuild	2024-03-24 19:10:58.000000000 +0100
-+++ firefox-126.0.ebuild	2024-05-14 07:42:43.000000000 +0200
+--- foofirefox-126.0.ebuild.orig	2024-05-14 07:42:43.000000000 +0200
++++ firefox-127.0.ebuild	2024-06-11 08:11:14.000000000 +0200
 @@ -3,9 +3,9 @@
  
  EAPI=8
  
--FIREFOX_PATCHSET="firefox-124-patches-01.tar.xz"
-+FIREFOX_PATCHSET="firefox-126-patches-01.tar.xz"
+-FIREFOX_PATCHSET="firefox-126-patches-01.tar.xz"
++FIREFOX_PATCHSET="firefox-127-patches-02.tar.xz"
  
--LLVM_COMPAT=( 16 17 )
-+LLVM_COMPAT=( 17 )
+-LLVM_COMPAT=( 17 )
++LLVM_COMPAT=( 17 18 )
  
  PYTHON_COMPAT=( python3_{10..12} )
  PYTHON_REQ_USE="ncurses,sqlite,ssl"
-@@ -63,7 +63,7 @@ LICENSE="MPL-2.0 GPL-2 LGPL-2.1"
- 
- IUSE="+clang cpu_flags_arm_neon dbus debug eme-free hardened hwaccel"
- IUSE+=" jack +jumbo-build libproxy lto openh264 pgo pulseaudio sndio selinux"
--IUSE+=" +system-av1 +system-harfbuzz +system-icu +system-jpeg +system-libevent +system-libvpx system-png system-python-libs +system-webp"
-+IUSE+=" +system-av1 +system-harfbuzz +system-icu +system-jpeg +system-libevent +system-libvpx system-png +system-webp"
- IUSE+=" +telemetry valgrind wayland wifi +X"
- 
+@@ -69,8 +69,6 @@ IUSE+=" +telemetry valgrind wayland wifi
  # Firefox-only IUSE
-@@ -73,7 +73,6 @@ IUSE+=" geckodriver +gmp-autoupdate"
- #   firefox-120.0/intl/components/src/TimeZone.cpp:345:3: error: use of undeclared identifier 'MOZ_TRY'
+ IUSE+=" geckodriver +gmp-autoupdate"
+ 
+-# "-jumbo-build +system-icu": build failure on firefox-120:
+-#   firefox-120.0/intl/components/src/TimeZone.cpp:345:3: error: use of undeclared identifier 'MOZ_TRY'
  REQUIRED_USE="|| ( X wayland )
  	debug? ( !system-av1 )
--	!jumbo-build? ( !system-icu )
  	pgo? ( lto )
- 	wifi? ( dbus )"
- 
-@@ -96,13 +95,8 @@ BDEPEND="${PYTHON_DEPS}
+@@ -95,7 +93,7 @@ BDEPEND="${PYTHON_DEPS}
  	>=dev-util/cbindgen-0.26.0
  	net-libs/nodejs
  	virtual/pkgconfig
--	!clang? ( >=virtual/rust-1.70 )
--	!elibc_glibc? (
--		|| (
--			dev-lang/rust
--			<dev-lang/rust-bin-1.73
--		)
--	)
-+	!clang? ( >=virtual/rust-1.74 )
-+	!elibc_glibc? ( dev-lang/rust )
+-	!clang? ( >=virtual/rust-1.74 )
++	!clang? ( >=virtual/rust-1.76 )
+ 	!elibc_glibc? ( dev-lang/rust )
  	amd64? ( >=dev-lang/nasm-2.14 )
  	x86? ( >=dev-lang/nasm-2.14 )
- 	pgo? (
-@@ -121,7 +115,7 @@ COMMON_DEPEND="${FF_ONLY_DEPEND}
+@@ -106,7 +104,10 @@ BDEPEND="${PYTHON_DEPS}
+ 			x11-apps/xhost
+ 		)
+ 		!X? (
+-			>=gui-libs/wlroots-0.15.1-r1[tinywl]
++			|| (
++				gui-wm/tinywl
++				<gui-libs/wlroots-0.17.3[tinywl(-)]
++			)
+ 			x11-misc/xkeyboard-config
+ 		)
+ 	)"
+@@ -115,7 +116,7 @@ COMMON_DEPEND="${FF_ONLY_DEPEND}
  	dev-libs/expat
  	dev-libs/glib:2
  	dev-libs/libffi:=
--	>=dev-libs/nss-3.98
-+	>=dev-libs/nss-3.99
+-	>=dev-libs/nss-3.99
++	>=dev-libs/nss-3.100
  	>=dev-libs/nspr-4.35
  	media-libs/alsa-lib
  	media-libs/fontconfig
-@@ -612,10 +606,6 @@ src_prepare() {
- 		rm -v "${WORKDIR}"/firefox-patches/*-LTO-Only-enable-LTO-*.patch || die
- 	fi
- 
--	if ! use ppc64; then
--		rm -v "${WORKDIR}"/firefox-patches/*ppc64*.patch || die
--	fi
--
- 	# Workaround for bgo#917599
- 	if has_version ">=dev-libs/icu-74.1" && use system-icu ; then
- 		eapply "${WORKDIR}"/firefox-patches/*-bmo-1862601-system-icu-74.patch
-@@ -641,6 +631,8 @@ src_prepare() {
- 			export RUST_TARGET="x86_64-unknown-linux-musl"
- 		elif use x86 ; then
- 			export RUST_TARGET="i686-unknown-linux-musl"
-+		elif use arm64 ; then
-+			export RUST_TARGET="aarch64-unknown-linux-musl"
- 		else
- 			die "Unknown musl chost, please post your rustc -vV along with emerge --info on Gentoo's bug #915651"
- 		fi
-@@ -1052,7 +1044,7 @@ src_configure() {
- 	fi
- 
- 	# elf-hack
--	# Filter "-z,pack-relative-relocs" and let the build system handle it instead. 
-+	# Filter "-z,pack-relative-relocs" and let the build system handle it instead.
- 	if use amd64 || use x86 ; then
- 		filter-flags "-z,pack-relative-relocs"
- 
-@@ -1062,8 +1054,9 @@ src_configure() {
- 		else
- 			mozconfig_add_options_ac 'relr elf-hack' --enable-elf-hack=relr
- 		fi
--	elif use ppc64 ; then
--		# '--disable-elf-hack' is not recognized on ppc64, bgo#917049
-+	elif use ppc64 || use riscv ; then
-+		# '--disable-elf-hack' is not recognized on ppc64/riscv,
-+		# see bgo #917049, #930046
- 		:;
- 	else
- 		mozconfig_add_options_ac 'disable elf-hack on non-supported arches' --disable-elf-hack
-@@ -1108,11 +1101,7 @@ src_configure() {
- 	# Use system's Python environment
- 	export PIP_NETWORK_INSTALL_RESTRICTED_VIRTUALENVS=mach
- 
--	if use system-python-libs; then
--		export MACH_BUILD_PYTHON_NATIVE_PACKAGE_SOURCE="system"
--	else
--		export MACH_BUILD_PYTHON_NATIVE_PACKAGE_SOURCE="none"
--	fi
-+	export MACH_BUILD_PYTHON_NATIVE_PACKAGE_SOURCE="none"
- 
- 	if ! use telemetry; then
- 		mozconfig_add_options_mk '-telemetry setting' "MOZ_CRASHREPORTER=0"
-@@ -1421,4 +1410,10 @@ pkg_postinst() {
- 		elog "See Gentoo bug #910309 or upstream bug #1843683."
- 		elog
- 	fi
-+
-+	if use geckodriver ; then
-+		ewarn "You have enabled the 'geckodriver' USE flag. Geckodriver is now"
-+		ewarn "packaged separately as net-misc/geckodriver and the use flag will be"
-+		ewarn "dropped from main Firefox package by Firefox 128.0 release."
-+	fi
- }
