firefox 129 and mid sysup

diff --git a/www-client/firefox/le.patch b/www-client/firefox/le.patch
--- a/www-client/firefox/le.patch
+++ b/www-client/firefox/le.patch
@@ -1,126 +1,136 @@
---- ffirefox-127.0.2.ebuild	2024-06-26 13:40:55.000000000 +0200
-+++ firefox-128.0.ebuild	2024-07-12 15:41:13.000000000 +0200
-@@ -3,7 +3,7 @@
- 
- EAPI=8
- 
--FIREFOX_PATCHSET="firefox-127-patches-02.tar.xz"
-+FIREFOX_PATCHSET="firefox-128-patches-04.tar.xz"
- 
- LLVM_COMPAT=( 17 18 )
- 
-@@ -67,7 +67,7 @@ IUSE+=" +system-av1 +system-harfbuzz +sy
- IUSE+=" +telemetry valgrind wayland wifi +X"
- 
- # Firefox-only IUSE
--IUSE+=" geckodriver +gmp-autoupdate"
-+IUSE+=" +gmp-autoupdate"
- 
- REQUIRED_USE="|| ( X wayland )
- 	debug? ( !system-av1 )
-@@ -116,7 +116,7 @@ COMMON_DEPEND="${FF_ONLY_DEPEND}
+--- ffirefox-128.0.3.ebuild.orig
++++ firefox-129.0.ebuild
+@@ -50,16 +50,14 @@
+ 	https://dev.gentoo.org/~juippis/mozilla/patchsets/${FIREFOX_PATCHSET}
+ )
+
+-SRC_URI="${MOZ_SRC_BASE_URI}/source/${MOZ_P}.source.tar.xz -> ${MOZ_P_DISTFILES}.source.tar.xz
+-	${PATCH_URIS[@]}"
+-
+ DESCRIPTION="Firefox Web Browser"
+ HOMEPAGE="https://www.mozilla.com/firefox"
+-
+-KEYWORDS="~amd64 ~arm64 ~ppc64 ~riscv ~x86"
+-
+-SLOT="rapid"
++SRC_URI="${MOZ_SRC_BASE_URI}/source/${MOZ_P}.source.tar.xz -> ${MOZ_P_DISTFILES}.source.tar.xz
++	${PATCH_URIS[@]}"
++S="${WORKDIR}/${PN}-${PV%_*}"
+ LICENSE="MPL-2.0 GPL-2 LGPL-2.1"
++SLOT="rapid"
++KEYWORDS="~amd64 ~arm64 ~ppc64 ~riscv ~x86"
+
+ IUSE="+clang cpu_flags_arm_neon dbus debug eme-free hardened hwaccel"
+ IUSE+=" jack +jumbo-build libproxy lto openh264 pgo pulseaudio sndio selinux"
+@@ -117,7 +115,7 @@
  	dev-libs/expat
  	dev-libs/glib:2
  	dev-libs/libffi:=
--	>=dev-libs/nss-3.100
-+	>=dev-libs/nss-3.101
+-	>=dev-libs/nss-3.101
++	>=dev-libs/nss-3.102
  	>=dev-libs/nspr-4.35
  	media-libs/alsa-lib
  	media-libs/fontconfig
-@@ -126,7 +126,7 @@ COMMON_DEPEND="${FF_ONLY_DEPEND}
- 	sys-libs/zlib
- 	virtual/freedesktop-icon-theme
- 	x11-libs/cairo
--	x11-libs/gdk-pixbuf
-+	x11-libs/gdk-pixbuf:2
- 	x11-libs/pango
- 	x11-libs/pixman
- 	dbus? (
-@@ -151,7 +151,7 @@ COMMON_DEPEND="${FF_ONLY_DEPEND}
- 		>=media-libs/harfbuzz-2.8.1:0=
- 	)
- 	system-icu? ( >=dev-libs/icu-73.1:= )
--	system-jpeg? ( >=media-libs/libjpeg-turbo-1.2.1 )
-+	system-jpeg? ( >=media-libs/libjpeg-turbo-1.2.1:= )
- 	system-libevent? ( >=dev-libs/libevent-2.1.12:0=[threads(+)] )
- 	system-libvpx? ( >=media-libs/libvpx-1.8.2:0=[postproc] )
- 	system-png? ( >=media-libs/libpng-1.6.35:0=[apng] )
-@@ -160,7 +160,6 @@ COMMON_DEPEND="${FF_ONLY_DEPEND}
- 	wayland? (
- 		>=media-libs/libepoxy-1.5.10-r1
- 		x11-libs/gtk+:3[wayland]
--		x11-libs/libxkbcommon[wayland]
- 	)
- 	wifi? (
- 		kernel_linux? (
-@@ -177,9 +176,7 @@ COMMON_DEPEND="${FF_ONLY_DEPEND}
- 		x11-libs/libXdamage
- 		x11-libs/libXext
- 		x11-libs/libXfixes
--		x11-libs/libxkbcommon[X]
- 		x11-libs/libXrandr
--		x11-libs/libXtst
- 		x11-libs/libxcb:=
+@@ -194,8 +192,6 @@
+ 		x11-libs/libSM
  	)"
- RDEPEND="${COMMON_DEPEND}
-@@ -270,6 +267,7 @@ MOZ_LANGS+=( oc )
- MOZ_LANGS+=( sc )
- MOZ_LANGS+=( sco )
- MOZ_LANGS+=( si )
-+MOZ_LANGS+=( skr )
- MOZ_LANGS+=( son )
- MOZ_LANGS+=( szl )
- MOZ_LANGS+=( ta )
-@@ -795,6 +793,7 @@ src_configure() {
- 		--disable-cargo-incremental \
- 		--disable-crashreporter \
- 		--disable-disk-remnant-avoidance \
-+		--disable-geckodriver \
- 		--disable-gpsd \
- 		--disable-install-strip \
- 		--disable-legacy-profile-creation \
-@@ -903,8 +902,6 @@ src_configure() {
- 
- 	use eme-free && mozconfig_add_options_ac '+eme-free' --disable-eme
- 
--	mozconfig_use_enable geckodriver
+
+-S="${WORKDIR}/${PN}-${PV%_*}"
 -
- 	if use hardened ; then
- 		mozconfig_add_options_ac "+hardened" --enable-hardening
- 		append-ldflags "-Wl,-z,relro -Wl,-z,now"
-@@ -986,6 +983,7 @@ src_configure() {
- 	mozconfig_use_enable debug
- 	if use debug ; then
- 		mozconfig_add_options_ac '+debug' --disable-optimize
-+		mozconfig_add_options_ac '+debug' --enable-jemalloc
- 		mozconfig_add_options_ac '+debug' --enable-real-time-tracing
- 	else
- 		mozconfig_add_options_ac 'Gentoo defaults' --disable-real-time-tracing
-@@ -1277,16 +1275,6 @@ src_install() {
- 		moz_install_xpi "${MOZILLA_FIVE_HOME}/distribution/extensions" "${langpacks[@]}"
+ # Allow MOZ_GMP_PLUGIN_LIST to be set in an eclass or
+ # overridden in the enviromnent (advanced hackers only)
+ if [[ -z "${MOZ_GMP_PLUGIN_LIST+set}" ]] ; then
+@@ -221,7 +217,8 @@
+
+ 		if use pgo ; then
+ 			if ! has_version -b "=sys-libs/compiler-rt-sanitizers-${LLVM_SLOT}*[profile]" ; then
+-				einfo "=sys-libs/compiler-rt-sanitizers-${LLVM_SLOT}*[profile] is missing! Cannot use LLVM slot ${LLVM_SLOT} ..." >&2
++				einfo "=sys-libs/compiler-rt-sanitizers-${LLVM_SLOT}*[profile] is missing!" >&2
++				einfo "Cannot use LLVM slot ${LLVM_SLOT} ..." >&2
+ 				return 1
+ 			fi
+ 		fi
+@@ -654,7 +651,8 @@
+ 		"${S}"/third_party/libwebrtc/build/toolchain/get_cpu_count.py || die "Failed sedding multiprocessing.cpu_count"
+
+ 	sed -i -e "s/multiprocessing.cpu_count()/$(makeopts_jobs)/" \
+-		"${S}"/third_party/libwebrtc/build/toolchain/get_concurrent_links.py || die "Failed sedding multiprocessing.cpu_count"
++		"${S}"/third_party/libwebrtc/build/toolchain/get_concurrent_links.py ||
++			die "Failed sedding multiprocessing.cpu_count"
+
+ 	sed -i -e "s/multiprocessing.cpu_count()/$(makeopts_jobs)/" \
+ 		"${S}"/third_party/python/gyp/pylib/gyp/input.py || die "Failed sedding multiprocessing.cpu_count"
+@@ -679,7 +677,6 @@
+
+ 	# Clear checksums from cargo crates we've manually patched.
+ 	# moz_clear_vendor_checksums xyz
+-	moz_clear_vendor_checksums proc-macro2
+
+ 	# Respect choice for "jumbo-build"
+ 	# Changing the value for FILES_PER_UNIFIED_FILE may not work, see #905431
+@@ -691,10 +688,12 @@
+ 		elog "if that fails try -jumbo-build before opening a bug report."
+ 		elog ""
+
+-		sed -i -e "s/\"FILES_PER_UNIFIED_FILE\", 16/\"FILES_PER_UNIFIED_FILE\", "${my_files_per_unified_file}"/" python/mozbuild/mozbuild/frontend/data.py ||
+-			die "Failed to adjust FILES_PER_UNIFIED_FILE in python/mozbuild/mozbuild/frontend/data.py"
+-		sed -i -e "s/FILES_PER_UNIFIED_FILE = 6/FILES_PER_UNIFIED_FILE = "${my_files_per_unified_file}"/" js/src/moz.build ||
+-			die "Failed to adjust FILES_PER_UNIFIED_FILE in js/src/moz.build"
++		sed -i -e "s/\"FILES_PER_UNIFIED_FILE\", 16/\"FILES_PER_UNIFIED_FILE\", "${my_files_per_unified_file}"/" \
++			python/mozbuild/mozbuild/frontend/data.py ||
++				die "Failed to adjust FILES_PER_UNIFIED_FILE in python/mozbuild/mozbuild/frontend/data.py"
++		sed -i -e "s/FILES_PER_UNIFIED_FILE = 6/FILES_PER_UNIFIED_FILE = "${my_files_per_unified_file}"/" \
++			js/src/moz.build ||
++				die "Failed to adjust FILES_PER_UNIFIED_FILE in js/src/moz.build"
  	fi
- 
--	# Install geckodriver
--	if use geckodriver ; then
--		einfo "Installing geckodriver into ${ED}${MOZILLA_FIVE_HOME} ..."
--		pax-mark m "${BUILD_DIR}"/dist/bin/geckodriver
--		exeinto "${MOZILLA_FIVE_HOME}"
--		doexe "${BUILD_DIR}"/dist/bin/geckodriver
--
--		dosym ${MOZILLA_FIVE_HOME}/geckodriver /usr/bin/geckodriver
--	fi
--
- 	# Install icons
- 	local icon_srcdir="${S}/browser/branding/official"
- 	local icon_symbolic_file="${FILESDIR}/icon/firefox-symbolic.svg"
-@@ -1411,10 +1399,4 @@ pkg_postinst() {
- 		elog "See Gentoo bug #910309 or upstream bug #1843683."
- 		elog
+
+ 	# Create build dir
+@@ -1223,7 +1222,7 @@
+
+ 	# Set dictionary path to use system hunspell
+ 	cat >>"${GENTOO_PREFS}" <<-EOF || die "failed to set spellchecker.dictionary_path pref"
+-	pref("spellchecker.dictionary_path",       "${EPREFIX}/usr/share/myspell");
++	pref("spellchecker.dictionary_path", "${EPREFIX}/usr/share/myspell");
+ 	EOF
+
+ 	# Force hwaccel prefs if USE=hwaccel is enabled
+@@ -1234,11 +1233,11 @@
+
+ 		if use wayland; then
+ 			cat >>"${GENTOO_PREFS}" <<-EOF || die "failed to set hwaccel wayland prefs"
+-			pref("gfx.x11-egl.force-enabled",          false);
++			pref("gfx.x11-egl.force-enabled", false);
+ 			EOF
+ 		else
+ 			cat >>"${GENTOO_PREFS}" <<-EOF || die "failed to set hwaccel x11 prefs"
+-			pref("gfx.x11-egl.force-enabled",          true);
++			pref("gfx.x11-egl.force-enabled", true);
+ 			EOF
+ 		fi
+
+@@ -1258,7 +1257,7 @@
+ 		for plugin in "${MOZ_GMP_PLUGIN_LIST[@]}" ; do
+ 			einfo "Disabling auto-update for ${plugin} plugin ..."
+ 			cat >>"${GENTOO_PREFS}" <<-EOF || die "failed to disable autoupdate for ${plugin} media plugin"
+-			pref("media.${plugin}.autoupdate",   false);
++			pref("media.${plugin}.autoupdate", false);
+ 			EOF
+ 		done
  	fi
--
--	if use geckodriver ; then
--		ewarn "You have enabled the 'geckodriver' USE flag. Geckodriver is now"
--		ewarn "packaged separately as net-misc/geckodriver and the use flag will be"
--		ewarn "dropped from main Firefox package by Firefox 128.0 release."
--	fi
- }
+@@ -1270,6 +1269,16 @@
+ 		EOF
+ 	fi
+
++	# Add telemetry config prefs, just in case something happens in future and telemetry build
++	# options stop working.
++	if ! use telemetry ; then
++		cat >>"${GENTOO_PREFS}" <<-EOF || die "failed to set telemetry prefs"
++		sticky_pref("toolkit.telemetry.dap_enabled", false);
++		pref("toolkit.telemetry.dap_helper", "");
++		pref("toolkit.telemetry.dap_leader", "");
++		EOF
++	fi
++
+ 	# Install language packs
+ 	local langpacks=( $(find "${WORKDIR}/language_packs" -type f -name '*.xpi') )
+ 	if [[ -n "${langpacks}" ]] ; then
diff --git a/www-client/firefox/moo.patch b/www-client/firefox/moo.patch
--- a/www-client/firefox/moo.patch
+++ b/www-client/firefox/moo.patch
@@ -1,10 +1,136 @@
---- foofirefox-128.0.ebuild
-+++ firefox-128.0.3.ebuild
-@@ -72,6 +72,7 @@
- REQUIRED_USE="|| ( X wayland )
- 	debug? ( !system-av1 )
- 	pgo? ( lto )
-+	wayland? ( dbus )
- 	wifi? ( dbus )"
+--- firefox-128.0.3.ebuild
++++ firefox-129.0.ebuild
+@@ -50,16 +50,14 @@
+ 	https://dev.gentoo.org/~juippis/mozilla/patchsets/${FIREFOX_PATCHSET}
+ )
 
- FF_ONLY_DEPEND="!www-client/firefox:0
+-SRC_URI="${MOZ_SRC_BASE_URI}/source/${MOZ_P}.source.tar.xz -> ${MOZ_P_DISTFILES}.source.tar.xz
+-	${PATCH_URIS[@]}"
+-
+ DESCRIPTION="Firefox Web Browser"
+ HOMEPAGE="https://www.mozilla.com/firefox"
+-
+-KEYWORDS="~amd64 ~arm64 ~ppc64 ~riscv ~x86"
+-
+-SLOT="rapid"
++SRC_URI="${MOZ_SRC_BASE_URI}/source/${MOZ_P}.source.tar.xz -> ${MOZ_P_DISTFILES}.source.tar.xz
++	${PATCH_URIS[@]}"
++S="${WORKDIR}/${PN}-${PV%_*}"
+ LICENSE="MPL-2.0 GPL-2 LGPL-2.1"
++SLOT="rapid"
++KEYWORDS="~amd64 ~arm64 ~ppc64 ~riscv ~x86"
+
+ IUSE="+clang cpu_flags_arm_neon dbus debug eme-free hardened hwaccel"
+ IUSE+=" jack +jumbo-build libproxy lto openh264 pgo pulseaudio sndio selinux"
+@@ -117,7 +115,7 @@
+ 	dev-libs/expat
+ 	dev-libs/glib:2
+ 	dev-libs/libffi:=
+-	>=dev-libs/nss-3.101
++	>=dev-libs/nss-3.102
+ 	>=dev-libs/nspr-4.35
+ 	media-libs/alsa-lib
+ 	media-libs/fontconfig
+@@ -194,8 +192,6 @@
+ 		x11-libs/libSM
+ 	)"
+
+-S="${WORKDIR}/${PN}-${PV%_*}"
+-
+ # Allow MOZ_GMP_PLUGIN_LIST to be set in an eclass or
+ # overridden in the enviromnent (advanced hackers only)
+ if [[ -z "${MOZ_GMP_PLUGIN_LIST+set}" ]] ; then
+@@ -221,7 +217,8 @@
+
+ 		if use pgo ; then
+ 			if ! has_version -b "=sys-libs/compiler-rt-sanitizers-${LLVM_SLOT}*[profile]" ; then
+-				einfo "=sys-libs/compiler-rt-sanitizers-${LLVM_SLOT}*[profile] is missing! Cannot use LLVM slot ${LLVM_SLOT} ..." >&2
++				einfo "=sys-libs/compiler-rt-sanitizers-${LLVM_SLOT}*[profile] is missing!" >&2
++				einfo "Cannot use LLVM slot ${LLVM_SLOT} ..." >&2
+ 				return 1
+ 			fi
+ 		fi
+@@ -654,7 +651,8 @@
+ 		"${S}"/third_party/libwebrtc/build/toolchain/get_cpu_count.py || die "Failed sedding multiprocessing.cpu_count"
+
+ 	sed -i -e "s/multiprocessing.cpu_count()/$(makeopts_jobs)/" \
+-		"${S}"/third_party/libwebrtc/build/toolchain/get_concurrent_links.py || die "Failed sedding multiprocessing.cpu_count"
++		"${S}"/third_party/libwebrtc/build/toolchain/get_concurrent_links.py ||
++			die "Failed sedding multiprocessing.cpu_count"
+
+ 	sed -i -e "s/multiprocessing.cpu_count()/$(makeopts_jobs)/" \
+ 		"${S}"/third_party/python/gyp/pylib/gyp/input.py || die "Failed sedding multiprocessing.cpu_count"
+@@ -681,7 +679,6 @@
+
+ 	# Clear checksums from cargo crates we've manually patched.
+ 	# moz_clear_vendor_checksums xyz
+-	moz_clear_vendor_checksums proc-macro2
+
+ 	# Respect choice for "jumbo-build"
+ 	# Changing the value for FILES_PER_UNIFIED_FILE may not work, see #905431
+@@ -693,10 +690,12 @@
+ 		elog "if that fails try -jumbo-build before opening a bug report."
+ 		elog ""
+
+-		sed -i -e "s/\"FILES_PER_UNIFIED_FILE\", 16/\"FILES_PER_UNIFIED_FILE\", "${my_files_per_unified_file}"/" python/mozbuild/mozbuild/frontend/data.py ||
+-			die "Failed to adjust FILES_PER_UNIFIED_FILE in python/mozbuild/mozbuild/frontend/data.py"
+-		sed -i -e "s/FILES_PER_UNIFIED_FILE = 6/FILES_PER_UNIFIED_FILE = "${my_files_per_unified_file}"/" js/src/moz.build ||
+-			die "Failed to adjust FILES_PER_UNIFIED_FILE in js/src/moz.build"
++		sed -i -e "s/\"FILES_PER_UNIFIED_FILE\", 16/\"FILES_PER_UNIFIED_FILE\", "${my_files_per_unified_file}"/" \
++			python/mozbuild/mozbuild/frontend/data.py ||
++				die "Failed to adjust FILES_PER_UNIFIED_FILE in python/mozbuild/mozbuild/frontend/data.py"
++		sed -i -e "s/FILES_PER_UNIFIED_FILE = 6/FILES_PER_UNIFIED_FILE = "${my_files_per_unified_file}"/" \
++			js/src/moz.build ||
++				die "Failed to adjust FILES_PER_UNIFIED_FILE in js/src/moz.build"
+ 	fi
+
+ 	# Create build dir
+@@ -1353,7 +1352,7 @@
+
+ 	# Set dictionary path to use system hunspell
+ 	cat >>"${GENTOO_PREFS}" <<-EOF || die "failed to set spellchecker.dictionary_path pref"
+-	pref("spellchecker.dictionary_path",       "${EPREFIX}/usr/share/myspell");
++	pref("spellchecker.dictionary_path", "${EPREFIX}/usr/share/myspell");
+ 	EOF
+
+ 	# Force hwaccel prefs if USE=hwaccel is enabled
+@@ -1364,11 +1363,11 @@
+
+ 		if use wayland; then
+ 			cat >>"${GENTOO_PREFS}" <<-EOF || die "failed to set hwaccel wayland prefs"
+-			pref("gfx.x11-egl.force-enabled",          false);
++			pref("gfx.x11-egl.force-enabled", false);
+ 			EOF
+ 		else
+ 			cat >>"${GENTOO_PREFS}" <<-EOF || die "failed to set hwaccel x11 prefs"
+-			pref("gfx.x11-egl.force-enabled",          true);
++			pref("gfx.x11-egl.force-enabled", true);
+ 			EOF
+ 		fi
+
+@@ -1388,7 +1387,7 @@
+ 		for plugin in "${MOZ_GMP_PLUGIN_LIST[@]}" ; do
+ 			einfo "Disabling auto-update for ${plugin} plugin ..."
+ 			cat >>"${GENTOO_PREFS}" <<-EOF || die "failed to disable autoupdate for ${plugin} media plugin"
+-			pref("media.${plugin}.autoupdate",   false);
++			pref("media.${plugin}.autoupdate", false);
+ 			EOF
+ 		done
+ 	fi
+@@ -1400,6 +1399,16 @@
+ 		EOF
+ 	fi
+
++	# Add telemetry config prefs, just in case something happens in future and telemetry build
++	# options stop working.
++	if ! use telemetry ; then
++		cat >>"${GENTOO_PREFS}" <<-EOF || die "failed to set telemetry prefs"
++		sticky_pref("toolkit.telemetry.dap_enabled", false);
++		pref("toolkit.telemetry.dap_helper", "");
++		pref("toolkit.telemetry.dap_leader", "");
++		EOF
++	fi
++
+ 	# Install language packs
+ 	local langpacks=( $(find "${WORKDIR}/language_packs" -type f -name '*.xpi') )
+ 	if [[ -n "${langpacks}" ]] ; then
