before firefox 122.0.1 ebuild mod

diff --git a/www-client/firefox/moo.patch b/www-client/firefox/moo.patch
--- a/www-client/firefox/moo.patch
+++ b/www-client/firefox/moo.patch
@@ -1,32 +1,18 @@
---- firefox-120.0.ebuild	2023-10-03 18:11:04.000000000 +0200
-+++ firefox-120.0.ebuild	2023-11-22 15:40:46.000000000 +0100
-@@ -3,9 +3,9 @@
+--- firefox-.0.ebuild.orig	2023-11-25 14:37:54.969821108 +0100
++++ firefox-122.0.1.ebuild	2023-11-25 14:38:19.086486879 +0100
+@@ -64,7 +64,8 @@ LICENSE="MPL-2.0 GPL-2 LGPL-2.1"
+ IUSE="+clang cpu_flags_arm_neon dbus debug eme-free hardened hwaccel"
+ IUSE+=" jack +jumbo-build libproxy lto openh264 pgo pulseaudio sndio selinux"
+ IUSE+=" +system-av1 +system-harfbuzz +system-icu +system-jpeg +system-libevent +system-libvpx system-png system-python-libs +system-webp"
+-IUSE+=" +telemetry valgrind wayland wifi +X"
++#IUSE+=" -telemetry wayland wifi +X"
++IUSE+=" -telemetry valgrind wayland wifi +X"
  
- EAPI=8
- 
--FIREFOX_PATCHSET="firefox-118-patches-02.tar.xz"
-+FIREFOX_PATCHSET="firefox-120-patches-01.tar.xz"
- 
--LLVM_MAX_SLOT=16
-+LLVM_MAX_SLOT=17
- 
- PYTHON_COMPAT=( python3_{10..11} )
- PYTHON_REQ_USE="ncurses,sqlite,ssl"
-@@ -69,8 +69,11 @@ IUSE+=" +telemetry valgrind wayland wifi
  # Firefox-only IUSE
  IUSE+=" geckodriver +gmp-autoupdate screencast"
- 
-+# "-jumbo-build +system-icu": build failure on firefox-120:
-+#   firefox-120.0/intl/components/src/TimeZone.cpp:345:3: error: use of undeclared identifier 'MOZ_TRY'
- REQUIRED_USE="|| ( X wayland )
- 	debug? ( !system-av1 )
-+	!jumbo-build? ( !system-icu )
- 	pgo? ( lto )
- 	wifi? ( dbus )"
- 
-@@ -81,6 +84,15 @@ FF_ONLY_DEPEND="!www-client/firefox:0
- BDEPEND="${PYTHON_DEPS}
- 	|| (
+@@ -93,6 +94,15 @@ BDEPEND="${PYTHON_DEPS}
+ 			)
+ 		)
  		(
 +			sys-devel/clang:17
 +			sys-devel/llvm:17
@@ -40,112 +26,268 @@
  			sys-devel/clang:16
  			sys-devel/llvm:16
  			clang? (
-@@ -102,10 +114,10 @@ BDEPEND="${PYTHON_DEPS}
+@@ -101,15 +111,6 @@ BDEPEND="${PYTHON_DEPS}
+ 				pgo? ( =sys-libs/compiler-rt-sanitizers-16*[profile] )
+ 			)
+ 		)
+-		(
+-			sys-devel/clang:15
+-			sys-devel/llvm:15
+-			clang? (
+-				sys-devel/lld:15
+-				virtual/rust:0/llvm-15
+-				pgo? ( =sys-libs/compiler-rt-sanitizers-15*[profile] )
+-			)
+-		)
+ 	)
  	app-alternatives/awk
  	app-arch/unzip
- 	app-arch/zip
--	>=dev-util/cbindgen-0.24.3
-+	>=dev-util/cbindgen-0.26.0
- 	net-libs/nodejs
- 	virtual/pkgconfig
--	!clang? ( >=virtual/rust-1.65 )
-+	!clang? ( >=virtual/rust-1.70 )
- 	amd64? ( >=dev-lang/nasm-2.14 )
- 	x86? ( >=dev-lang/nasm-2.14 )
- 	pgo? (
-@@ -124,7 +136,7 @@ COMMON_DEPEND="${FF_ONLY_DEPEND}
- 	dev-libs/expat
- 	dev-libs/glib:2
- 	dev-libs/libffi:=
--	>=dev-libs/nss-3.93
-+	>=dev-libs/nss-3.94
- 	>=dev-libs/nspr-4.35
- 	media-libs/alsa-lib
- 	media-libs/fontconfig
-@@ -138,7 +150,6 @@ COMMON_DEPEND="${FF_ONLY_DEPEND}
- 	x11-libs/pango
- 	x11-libs/pixman
- 	dbus? (
--		dev-libs/dbus-glib
- 		sys-apps/dbus
- 	)
- 	jack? ( virtual/jack )
-@@ -174,7 +185,6 @@ COMMON_DEPEND="${FF_ONLY_DEPEND}
- 	)
- 	wifi? (
- 		kernel_linux? (
--			dev-libs/dbus-glib
- 			net-misc/networkmanager
- 			sys-apps/dbus
- 		)
-@@ -650,6 +660,12 @@ src_prepare() {
- 		rm -v "${WORKDIR}"/firefox-patches/*ppc64*.patch || die
- 	fi
- 
-+	# Workaround for bgo#917599
-+	if has_version ">=dev-libs/icu-74.1" && use system-icu ; then
-+		eapply "${WORKDIR}"/firefox-patches/0028-bmo-1862601-system-icu-74.patch
-+	fi
-+	rm -v "${WORKDIR}"/firefox-patches/0028-bmo-1862601-system-icu-74.patch || die
-+
- 	eapply "${WORKDIR}/firefox-patches"
- 
- 	# Allow user to apply any additional patches without modifing ebuild
-@@ -917,6 +933,9 @@ src_configure() {
- 	if use hardened ; then
- 		mozconfig_add_options_ac "+hardened" --enable-hardening
- 		append-ldflags "-Wl,-z,relro -Wl,-z,now"
-+
-+		# Increase the FORTIFY_SOURCE value, #910071.
-+		sed -i -e '/-D_FORTIFY_SOURCE=/s:2:3:' "${S}"/build/moz.configure/toolchain.configure || die
- 	fi
- 
- 	local myaudiobackends=""
-@@ -1048,31 +1067,23 @@ src_configure() {
+@@ -607,23 +608,23 @@ pkg_setup() {
+ 			ewarn "/dev/shm is not mounted -- expect build failures!"
  		fi
- 	fi
  
--	if use clang ; then
--		# https://bugzilla.mozilla.org/show_bug.cgi?id=1482204
--		# https://bugzilla.mozilla.org/show_bug.cgi?id=1483822
--		# toolkit/moz.configure Elfhack section: target.cpu in ('arm', 'x86', 'x86_64')
--		local disable_elf_hack=
--		if use amd64 ; then
--			disable_elf_hack=yes
--		elif use x86 ; then
--			disable_elf_hack=yes
--		elif use arm ; then
--			disable_elf_hack=yes
+-		# Google API keys (see http://www.chromium.org/developers/how-tos/api-keys)
+-		# Note: These are for Gentoo Linux use ONLY. For your own distribution, please
+-		# get your own set of keys.
+-		if [[ -z "${MOZ_API_KEY_GOOGLE+set}" ]] ; then
+-			MOZ_API_KEY_GOOGLE="AIzaSyDEAOvatFogGaPi0eTgsV_ZlEzx0ObmepsMzfAc"
 -		fi
 -
--		if [[ -n ${disable_elf_hack} ]] ; then
--			mozconfig_add_options_ac 'elf-hack is broken when using Clang' --disable-elf-hack
+-		if [[ -z "${MOZ_API_KEY_LOCATION+set}" ]] ; then
+-			MOZ_API_KEY_LOCATION="AIzaSyB2h2OuRgGaPicUgy5N-5hsZqiPW6sH3n_rptiQ"
 -		fi
--	elif tc-is-gcc ; then
--		if ver_test $(gcc-fullversion) -ge 10 ; then
--			einfo "Forcing -fno-tree-loop-vectorize to workaround GCC bug, see bug 758446 ..."
--			append-cxxflags -fno-tree-loop-vectorize
-+	# elf-hack
-+	if use amd64 || use x86 ; then
-+		if tc-ld-is-mold ; then
-+			# relr-elf-hack is currently broken with mold, bgo#916259
-+			mozconfig_add_options_ac 'disable elf-hack with mold linker' --disable-elf-hack
-+		else
-+			if use clang ; then
-+				mozconfig_add_options_ac 'relr elf-hack with clang' --enable-elf-hack=relr
-+			else
-+				mozconfig_add_options_ac 'legacy elf-hack with gcc' --enable-elf-hack=legacy
-+			fi
+-
+-		# Mozilla API keys (see https://location.services.mozilla.com/api)
+-		# Note: These are for Gentoo Linux use ONLY. For your own distribution, please
+-		# get your own set of keys.
+-		if [[ -z "${MOZ_API_KEY_MOZILLA+set}" ]] ; then
+-			MOZ_API_KEY_MOZILLA="edb3d487-3a84-46m0ap1e3-9dfd-92b5efaaa005"
+-		fi
++#		# Google API keys (see http://www.chromium.org/developers/how-tos/api-keys)
++#		# Note: These are for Gentoo Linux use ONLY. For your own distribution, please
++#		# get your own set of keys.
++#		if [[ -z "${MOZ_API_KEY_GOOGLE+set}" ]] ; then
++#			MOZ_API_KEY_GOOGLE="AIzaSyDEAOvatFogGaPi0eTgsV_ZlEzx0ObmepsMzfAc"
++#		fi
++#
++#		if [[ -z "${MOZ_API_KEY_LOCATION+set}" ]] ; then
++#			MOZ_API_KEY_LOCATION="AIzaSyB2h2OuRgGaPicUgy5N-5hsZqiPW6sH3n_rptiQ"
++#		fi
++#
++#		# Mozilla API keys (see https://location.services.mozilla.com/api)
++#		# Note: These are for Gentoo Linux use ONLY. For your own distribution, please
++#		# get your own set of keys.
++#		if [[ -z "${MOZ_API_KEY_MOZILLA+set}" ]] ; then
++#			MOZ_API_KEY_MOZILLA="edb3d487-3a84-46m0ap1e3-9dfd-92b5efaaa005"
++#		fi
+ 
+ 		# Ensure we use C locale when building, bug #746215
+ 		export LC_ALL=C
+@@ -692,6 +693,8 @@ src_prepare() {
+ 		"${S}"/python/mozbuild/mozbuild/configure/check_debug_ranges.py \
+ 		|| die "sed failed to set toolchain prefix"
+ 
++	#Allow disabling ccache stats here otherwise you get this: https://bugzilla.mozilla.org/show_bug.cgi?id=1742849
++	#or similar, like: Failed to parse ccache stats output: 'Uncacheable/Compiler produced empty output' '6038'
+ 	sed -i \
+ 		-e 's/ccache_stats = None/return None/' \
+ 		"${S}"/python/mozbuild/mozbuild/controller/building.py \
+@@ -725,10 +728,11 @@ src_prepare() {
+ 	BUILD_DIR="${WORKDIR}/${PN}_build"
+ 	mkdir -p "${BUILD_DIR}" || die
+ 
+-	# Write API keys to disk
+-	echo -n "${MOZ_API_KEY_GOOGLE//gGaPi/}" > "${S}"/api-google.key || die
+-	echo -n "${MOZ_API_KEY_LOCATION//gGaPi/}" > "${S}"/api-location.key || die
+-	echo -n "${MOZ_API_KEY_MOZILLA//m0ap1/}" > "${S}"/api-mozilla.key || die
++	## Write API keys to disk
++	#echo -n "${MOZ_API_KEY_GOOGLE//gGaPi/}" > "${S}"/api-google.key || die
++	#echo -n "${MOZ_API_KEY_LOCATION//gGaPi/}" > "${S}"/api-location.key || die
++	#echo -n "${MOZ_API_KEY_MOZILLA//m0ap1/}" > "${S}"/api-mozilla.key || die
++	rm -f "${S}"/api-google.key "${S}"/api-location.key "${S}"/api-mozilla.key
+ 
+ 	xdg_environment_reset
+ }
+@@ -813,6 +817,48 @@ src_configure() {
+ 		export MOZILLA_OFFICIAL=1
+ 	fi
+ 
++	#TODO: why did I do these before the other settings? wouldn't they potentially get overridden?!
++	#mozconfig_add_options_ac 'gotchas' \
++	#	--disable-more-deterministic
++	#^ because 84 failed tests(and Object's keys order is sorted!ie. it breaks the web): https://bugs.gentoo.org/717374 and https://bugzilla.mozilla.org/show_bug.cgi?id=1542951
++	#08 may 2021: www-client/firefox-88.0.1:  0:01.89 mozbuild.configure.options.InvalidOptionError: Unknown option: --disable-more-deterministic
++
++	mozconfig_add_options_ac 'just making sure' \
++		--disable-artifact-builds
++	# https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Build_Instructions/Artifact_builds
++
++
++		#--without-ccache \
++	mozconfig_add_options_ac 'with ccache' \
++		--with-ccache=/usr/bin/ccache
++
++
++	# 0:02.41 mozbuild.configure.options.InvalidOptionError: --enable-system-ffi is not available in this configuration
++		#--with-system-ffi \
++	# 0:02.39 mozbuild.configure.options.InvalidOptionError: --with-system-ffi is not available in this configuration
++
++	#mozconfig_add_options_ac 'probably needs to be enabled' \
++	#	--disable-ctypes
++	#XXX: ^ that --disable-ctypes will cause --enable-system-ffi to not be recognized as valid option!
++
++		#--enable-cpp-rtti \
++	mozconfig_add_options_ac 'must be enabled or else --enable-system-ffi to not be recognized as valid option, at least!' \
++		--enable-ctypes
++	#js-ctypes allows application and extension code to call back and forth to native code written in C. C++ support is possible through vtable pointers see Using COM from js-ctypes.
++#src: https://developer.mozilla.org/en-US/docs/Mozilla/js-ctypes
++#XXX: if you disable this, you'll get the following(maybe also the core dump because of it): firefox-hg $ ./mach run
++# 0:00.89 /tmp/obj-x86_64-pc-linux-gnu/dist/bin/firefox -no-remote -profile /tmp/obj-x86_64-pc-linux-gnu/tmp/scratch_user
++#JavaScript error: resource://gre/modules/osfile/osfile_shared_allthreads.jsm, line 92: NS_ERROR_FILE_NOT_FOUND: Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIXPCComponents_Utils.import]
++#[27108] WARNING: Cannot create startup observer : service,@mozilla.org/weave/service;1: file /home/z/build/1packages/firefox-hg/makepkg_pacman/firefox-hg/src/firefox-hg/embedding/components/appstartup/nsAppStartupNotifier.cpp, line 81
++
++	#removed from 'Gentoo default':
++		#--allow-addon-sideload \
++		#^  if update channel is esr then this is true! so careful!
++		#--without-ccache \
++
++		#--allow-addon-sideload \
++		#--without-ccache \
++
+ 	mozconfig_add_options_ac 'Gentoo default' \
+ 		--allow-addon-sideload \
+ 		--disable-cargo-incremental \
+@@ -852,13 +898,74 @@ src_configure() {
+ 		--x-libraries="${ESYSROOT}/usr/$(get_libdir)"
+ 
+ 	# Set update channel
+-	local update_channel=release
+-	[[ -n ${MOZ_ESR} ]] && update_channel=esr
+-	mozconfig_add_options_ac '' --update-channel=${update_channel}
++	#local update_channel=release
++	#[[ -n ${MOZ_ESR} ]] && update_channel=esr
++	#mozconfig_add_options_ac '' --update-channel=${update_channel}
++	mozconfig_add_options_ac 'from old mozconfig' --disable-update-channel
++
++		#on 97.0.2, 08march2022 the following options don't exist anymore:
++		#'--enable-extensions=default,-skipgnomevfs,-skipgio' \ # 0:01.62 mozbuild.configure.options.InvalidOptionError: Unknown option: --enable-extensions
++		#--disable-tasktracer \
++		#--enable-xul \
++		#on 103.0 28 july 2022, doesn't exist:
++		#--disable-verify-mar \
++
++	# spacer
++
++	mozconfig_add_options_ac 'from old mozconfig' \
++		--disable-valgrind \
++		--disable-jprof \
++		--disable-instruments \
++		--disable-callgrind \
++		--disable-dtrace \
++		--disable-libproxy \
++		--disable-accessibility \
++		--disable-webrtc \
++		--disable-raw \
++		--disable-wmf \
++		--enable-ffmpeg \
++		--disable-system-extension-dirs \
++		--disable-parental-controls \
++		--enable-sandbox \
++		--disable-logrefcnt \
++		--disable-dump-painting \
++		--disable-stdcxx-compat \
++		--disable-startupcache \
++		--disable-webspeech \
++		--disable-synth-speechd \
++		--disable-webspeechtestbackend \
++		--disable-tests \
++		--disable-vtune
+ 
+-	if ! use x86 && [[ ${CHOST} != armv*h* ]] ; then
+-		mozconfig_add_options_ac '' --enable-rust-simd
+-	fi
++	# in firefox 118.0.1
++	# 0:00.81 mozbuild.configure.options.InvalidOptionError: Unknown option: --enable-fmp4
++		#--enable-fmp4 \
++
++
++	#see more flags in ${WORKDIR}/firefox-83.0/toolkit/moz.configure
++
++	#FIXME: can't disable printing due to errors because it's not guarded, ie. firefox devs don't expect it to ever be disabled so they don't compile against it.
++		#--disable-printing \
++		#16:19.17 /var/tmp/portage/www-client/firefox-83.0/work/firefox-83.0/widget/nsPrintSettingsImpl.cpp:821:24: error: use of undeclared identifier 'PR_GetEnv'
++	mozconfig_add_options_ac 'possible source of issues unless toggled' \
++		--disable-profiling \
++		--disable-dmd \
++		--disable-cpp-rtti
++			# #DMD (short for "dark matter detector") is a heap profiler within Firefox. https://developer.mozilla.org/en-US/docs/Mozilla/Performance/DMD
++
++
++	#--disable-system-pixman #used to be disabled on archlinux because:  ^ can't find pixman.h !
++	# already handled when using USE=clang :: --disable-elf-hack
++	# --------------
++#	if ! use x86 && [[ ${CHOST} != armv*h* ]] ; then
++#		mozconfig_add_options_ac '' --enable-rust-simd
++#		#well this gives me errors like this:
++## 4:01.36 error: unrecognized platform-specific intrinsic function: `simd_shuffle2`
++## 4:01.36   --> /var/tmp/portage/www-client/firefox-118.0.1/work/firefox-118.0.1/third_party/rust/packed_simd_2/src/codegen/llvm.rs:10:5
++## 4:01.36    |
++## 4:01.36 10 |     pub fn simd_shuffle2<T, U>(x: T, y: T, idx: [u32; 2]) -> U;
++## 4:01.36    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
++#	fi
+ 
+ 	# For future keywording: This is currently (97.0) only supported on:
+ 	# amd64, arm, arm64 & x86.
+@@ -1008,10 +1115,15 @@ src_configure() {
+ 
+ 	mozconfig_use_enable debug
+ 	if use debug ; then
+-		mozconfig_add_options_ac '+debug' --disable-optimize
++		#mozconfig_add_options_ac '+debug' --disable-optimize
++		mozconfig_add_options_ac '+debug but do we want it for JS too? say yes for now' --enable-debug-js-modules
+ 		mozconfig_add_options_ac '+debug' --enable-real-time-tracing
++		#^ i haven't checked this to see if i need it or i don't!
+ 	else
+-		mozconfig_add_options_ac 'Gentoo defaults' --disable-real-time-tracing
++		mozconfig_add_options_ac 'normal non-debug build' --disable-debug-js-modules
++	fi
++	mozconfig_add_options_ac 'Gentoo defaults' --disable-real-time-tracing
++	#the -ggdb thing isn't dependent on USE=debug from now on:
+ 
+ 		if is-flag '-g*' ; then
+ 			if use clang ; then
+@@ -1036,7 +1148,7 @@ src_configure() {
+ 		else
+ 			mozconfig_add_options_ac "Gentoo default" --enable-optimize=-O2
  		fi
 -	fi
--
--	if use elibc_musl && use arm64 ; then
--		mozconfig_add_options_ac 'elf-hack is broken when using musl/arm64' --disable-elf-hack
-+	elif use ppc64 ; then
-+		# '--disable-elf-hack' is not recognized on ppc64, bgo#917049
-+		:;
-+	else
-+		mozconfig_add_options_ac 'disable elf-hack on non-supported arches' --disable-elf-hack
- 	fi
++	#fi
  
- 	# Additional ARCH support
+ 	# Debug flag was handled via configure
+ 	filter-flags '-g*'
+@@ -1137,6 +1249,25 @@ src_configure() {
+ 
+ 	# Disable notification when build system has finished
+ 	export MOZ_NOSPAM=1
++	#me
++	export -n MOZ_TELEMETRY_REPORTING
++	unset MOZ_TELEMETRY_REPORTING
++
++	#unsure if any effect: (but a patch is already rendering the use of this moot)
++	export -n MOZ_TELEMETRY_ON_BY_DEFAULT
++	unset MOZ_TELEMETRY_ON_BY_DEFAULT
++
++	#actually forget this, I'm patching it to FALSE in sources! 08 March 2022
++	##export MOZ_ADDON_SIGNING=1 #yup this was 1 even tho MOZ_REQUIRE_SIGNING=0
++	#export MOZ_ADDON_SIGNING=0 #this setting may not be used at all currently on 97.0.2 but just setting it to 0 anyway
++	##export MOZ_REQUIRE_SIGNING=0 # 0:01.63 mozbuild.configure.options.InvalidOptionError: MOZ_REQUIRE_SIGNING takes 0 values
++	#export -n MOZ_REQUIRE_SIGNING
++	#unset MOZ_REQUIRE_SIGNING
++	#MOZ_REQUIRE_SIGNING=
++	##^yup, it should be empty and work as if it's set to disabled!
++	#export MOZ_REQUIRE_SIGNING
++	#end of me
++
+ 
+ 	# Portage sets XARGS environment variable to "xargs -r" by default which
+ 	# breaks build system's check_prog() function which doesn't support arguments
