rust 1.75.0-r1

diff --git a/dev-lang/rust/moo.patch b/dev-lang/rust/moo.patch
--- a/dev-lang/rust/moo.patch
+++ b/dev-lang/rust/moo.patch
@@ -1,70 +1,126 @@
---- rust-1.0.ebuild.orig	2023-10-07 11:10:44.000000000 +0200
-+++ rust-1.74.1.ebuild	2023-10-09 19:42:05.921321082 +0200
-@@ -229,6 +229,8 @@ pre_build_checks() {
- 	eshopts_pop
- 	M=$(( $(usex system-bootstrap 0 1024) + ${M} ))
- 	M=$(( $(usex doc 256 0) + ${M} ))
-+	M=$(( 61000 + ${M} )) #takes 61G so to be sure add wtw else they think it would take, for crazy safety.
-+	#current ebuild (29nov2020) took 60mins to compile (mitigations=2) and 60G in /var/tmp/portage (oddly 610M left even tho it was a 64G ext4 zram
- 	CHECKREQS_DISK_BUILD=${M}M check-reqs_pkg_${EBUILD_PHASE}
- }
+--- ust-1.74.1.ebuild.orig	2024-02-07 16:20:29.520294390 +0100
++++ rust-1.75.0-r1.ebuild	2024-02-11 07:10:44.000000000 +0100
+@@ -19,7 +19,7 @@ else
+ 	SLOT="stable/${ABI_VER}"
+ 	MY_P="rustc-${PV}"
+ 	SRC="${MY_P}-src.tar.xz"
+-	KEYWORDS="amd64 ~arm arm64 ~loong ~mips ppc ppc64 ~riscv sparc ~x86"
++	KEYWORDS="~amd64 ~arm ~arm64 ~loong ~mips ~ppc ~ppc64 ~riscv ~sparc ~x86"
+ fi
  
-@@ -355,6 +357,7 @@ src_configure() {
- 		optimize = $(toml_usex !debug)
- 		release-debuginfo = $(toml_usex debug)
- 		assertions = $(toml_usex debug)
-+		ccache = "/usr/bin/ccache"
- 		ninja = true
- 		targets = "${LLVM_TARGETS// /;}"
- 		experimental-targets = ""
-@@ -400,10 +403,13 @@ src_configure() {
- 		vendor = true
- 		extended = true
- 		tools = [${tools}]
-+		# Verbosity level: 0 == not verbose, 1 == verbose, 2 == very verbose
- 		verbose = 2
- 		sanitizers = false
- 		profiler = $(toml_usex profiler)
- 		cargo-native-static = false
-+		low-priority = true
-+		print-step-timings = true
- 		[install]
- 		prefix = "${EPREFIX}/usr/lib/${PN}/${PV}"
- 		sysconfdir = "etc"
-@@ -418,10 +424,16 @@ src_configure() {
- 		debug = $(toml_usex debug)
- 		debug-assertions = $(toml_usex debug)
- 		debug-assertions-std = $(toml_usex debug)
--		debuginfo-level = $(usex debug 2 0)
--		debuginfo-level-rustc = $(usex debug 2 0)
--		debuginfo-level-std = $(usex debug 2 0)
--		debuginfo-level-tools = $(usex debug 2 0)
+ RUST_STAGE0_VERSION="1.$(($(ver_cut 2) - 1)).0"
+@@ -163,10 +163,14 @@ RESTRICT="test"
+ VERIFY_SIG_OPENPGP_KEY_PATH=/usr/share/openpgp-keys/rust.asc
+ 
+ PATCHES=(
++	"${FILESDIR}"/1.75.0-musl-dynamic-linking.patch
++	"${FILESDIR}"/1.74.1-cross-compile-libz.patch
+ 	#"${FILESDIR}"/1.72.0-bump-libc-deps-to-0.2.146.patch  # pending refresh
+ 	"${FILESDIR}"/1.70.0-ignore-broken-and-non-applicable-tests.patch
+-	"${FILESDIR}"/1.62.1-musl-dynamic-linking.patch
+ 	"${FILESDIR}"/1.67.0-doc-wasm.patch
++	# This patch shouldn't be necessary for later versions of Rust because its
++	# code was backported from master.
++	"${FILESDIR}"/1.75.0-handle-vendored-sources.patch
+ )
+ 
+ S="${WORKDIR}/${MY_P}-src"
+@@ -184,7 +188,7 @@ bootstrap_rust_version_check() {
+ 	[[ ${MERGE_TYPE} == binary ]] && return
+ 	local rustc_wanted="$(ver_cut 1).$(($(ver_cut 2) - 1))"
+ 	local rustc_toonew="$(ver_cut 1).$(($(ver_cut 2) + 1))"
+-	local rustc_version=( $(eselect --brief rust show 2>/dev/null) )
++	local rustc_version=( $(eselect --brief --root="${BROOT}" rust show 2>/dev/null) )
+ 	rustc_version=${rustc_version[0]#rust-bin-}
+ 	rustc_version=${rustc_version#rust-}
+ 
+@@ -256,6 +260,18 @@ pkg_setup() {
+ 	python-any-r1_pkg_setup
+ 
+ 	export LIBGIT2_NO_PKG_CONFIG=1 #749381
++	if tc-is-cross-compiler; then
++		export PKG_CONFIG_ALLOW_CROSS=1
++		export PKG_CONFIG_PATH="${ROOT}/usr/$(get_libdir)/pkgconfig"
++		export OPENSSL_INCLUDE_DIR="${ROOT}/usr/include"
++		export OPENSSL_LIB_DIR="${ROOT}/usr/$(get_libdir)"
 +
-+		debuginfo-level = 2
-+		debuginfo-level-rustc = 2
-+		debuginfo-level-std = 2
-+		debuginfo-level-tools = 2
-+		#debuginfo-level = $(usex debug 2 0)
-+		#debuginfo-level-rustc = $(usex debug 2 0)
-+		#debuginfo-level-std = $(usex debug 2 0)
-+		#debuginfo-level-tools = $(usex debug 2 0)
-+
++		use system-bootstrap || die "USE=system-bootstrap is required when cross-compiling"
++		use system-llvm && die "USE=system-llvm not allowed when cross-compiling"
++		local cross_llvm_target="$(llvm_tuple_to_target "${CBUILD}")"
++		use "llvm_targets_${cross_llvm_target}" || \
++			die "Must enable LLVM_TARGETS=${cross_llvm_target} matching CBUILD=${CBUILD} when cross-compiling"
++	fi
+ 
+ 	use system-bootstrap && bootstrap_rust_version_check
+ 
+@@ -298,7 +314,7 @@ src_prepare() {
+ 	if ! use system-bootstrap; then
+ 		has_version sys-devel/gcc || esetup_unwind_hack
+ 		local rust_stage0_root="${WORKDIR}"/rust-stage0
+-		local rust_stage0="rust-${RUST_STAGE0_VERSION}-$(rust_abi)"
++		local rust_stage0="rust-${RUST_STAGE0_VERSION}-$(rust_abi "${CBUILD}")"
+ 
+ 		"${WORKDIR}/${rust_stage0}"/install.sh --disable-ldconfig \
+ 			--without=rust-docs-json-preview,rust-docs --destdir="${rust_stage0_root}" --prefix=/ || die
+@@ -321,7 +337,7 @@ src_configure() {
+ 		if use system-llvm; then
+ 			# un-hardcode rust-lld linker for this target
+ 			# https://bugs.gentoo.org/715348
+-			sed -i '/linker:/ s/rust-lld/wasm-ld/' compiler/rustc_target/src/spec/wasm_base.rs || die
++			sed -i '/linker:/ s/rust-lld/wasm-ld/' compiler/rustc_target/src/spec/base/wasm.rs || die
+ 		fi
+ 	fi
+ 	rust_targets="${rust_targets#,}"
+@@ -347,6 +363,8 @@ src_configure() {
+ 	[[ -d ${rust_stage0_root} ]] || die "${rust_stage0_root} is not a directory"
+ 
+ 	rust_target="$(rust_abi)"
++	rust_build="$(rust_abi "${CBUILD}")"
++	rust_host="$(rust_abi "${CHOST}")"
+ 
+ 	local cm_btype="$(usex debug DEBUG RELEASE)"
+ 	cat <<- _EOF_ > "${S}"/config.toml
+@@ -378,17 +396,24 @@ src_configure() {
+ 		enable-warnings = false
+ 		[llvm.build-config]
+ 		CMAKE_VERBOSE_MAKEFILE = "ON"
+-		CMAKE_C_FLAGS_${cm_btype} = "${CFLAGS}"
+-		CMAKE_CXX_FLAGS_${cm_btype} = "${CXXFLAGS}"
+-		CMAKE_EXE_LINKER_FLAGS_${cm_btype} = "${LDFLAGS}"
+-		CMAKE_MODULE_LINKER_FLAGS_${cm_btype} = "${LDFLAGS}"
+-		CMAKE_SHARED_LINKER_FLAGS_${cm_btype} = "${LDFLAGS}"
+-		CMAKE_STATIC_LINKER_FLAGS_${cm_btype} = "${ARFLAGS}"
++		$(if ! tc-is-cross-compiler; then
++			# When cross-compiling, LLVM is compiled twice, once for host and
++			# once for target.  Unfortunately, this build configuration applies
++			# to both, which means any flags applicable to one target but not
++			# the other will break.  Conditionally disable respecting user
++			# flags when cross-compiling.
++			echo "CMAKE_C_FLAGS_${cm_btype} = \"${CFLAGS}\""
++			echo "CMAKE_CXX_FLAGS_${cm_btype} = \"${CXXFLAGS}\""
++			echo "CMAKE_EXE_LINKER_FLAGS_${cm_btype} = \"${LDFLAGS}\""
++			echo "CMAKE_MODULE_LINKER_FLAGS_${cm_btype} = \"${LDFLAGS}\""
++			echo "CMAKE_SHARED_LINKER_FLAGS_${cm_btype} = \"${LDFLAGS}\""
++			echo "CMAKE_STATIC_LINKER_FLAGS_${cm_btype} = \"${ARFLAGS}\""
++		fi)
+ 		[build]
+ 		build-stage = 2
+ 		test-stage = 2
+-		build = "${rust_target}"
+-		host = ["${rust_target}"]
++		build = "${rust_build}"
++		host = ["${rust_host}"]
+ 		target = [${rust_targets}]
+ 		cargo = "${rust_stage0_root}/bin/cargo"
+ 		rustc = "${rust_stage0_root}/bin/rustc"
+@@ -426,7 +451,9 @@ src_configure() {
  		debuginfo-level-tests = 0
  		backtrace = true
  		incremental = false
-@@ -445,8 +457,13 @@ src_configure() {
- 		lto = "$(usex lto fat off)"
- 		[dist]
- 		src-tarball = false
--		compression-formats = ["xz"]
--		compression-profile = "balanced"
-+		# Available options: fast, balanced, best
-+		compression-profile = "fast"
-+		compression-formats = ["none"]
-+		#patch made!'none' here means .tar only! or don't set any value here! oldcomments://nvm patch not made! //keep 'gz' here so that 0600_fabricate_neutering_try2_just_tar_not_gz_or_xz_for_rust_1_52_0.patch applies neatly
-+		#doneTODO: try compression-formats 'cat'(not valid!) or just make sure it doesn't use any! However list must not be empty! as per https://github.com/rust-lang/rust/blob/abf3ec5b3353be973b18269fcdda76a59743f235/config.toml.example#L696 see: https://github.com/rust-lang/rust-installer/issues/110
-+		#missing-tools = false
-+		#^ this won't work (either with =false or =true), it fails to compile miri even though USE=-miri due to /var/db/repos/gentoo/profiles/base/package.use.mask:30 so it has to be =true
- 	_EOF_
- 
- 	for v in $(multilib_get_enabled_abi_pairs); do
+-		default-linker = "$(tc-getCC)"
++		$(if ! tc-is-cross-compiler; then
++			echo "default-linker = \"$(tc-getCC)\""
++		fi)
+ 		parallel-compiler = $(toml_usex parallel-compiler)
+ 		channel = "$(usex nightly nightly stable)"
+ 		description = "gentoo"
